import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1758699367517 implements MigrationInterface {
    name = 'AutoGenerated1758699367517'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cognito_id" character varying(190)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying(190) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(40) NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "login_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otp" jsonb`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d9dea74916617da4a95c8cce52" ON "users" ("cognito_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_d9dea74916617da4a95c8cce52"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otp"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "login_count"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cognito_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(120)`);
    }

}
