import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1758948161842 implements MigrationInterface {
    name = 'AutoGenerated1758948161842'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(190) NOT NULL, "identity_sub" character varying(190), "cognito_id" character varying(190), "full_name" character varying(190) NOT NULL, "phone_number" character varying(20), "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "role" character varying(40) NOT NULL DEFAULT 'USER', "is_verified" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "login_count" integer NOT NULL DEFAULT '0', "last_login" TIMESTAMP, "otp" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_69e1783e301281de8f86190080" ON "users" ("identity_sub") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d9dea74916617da4a95c8cce52" ON "users" ("cognito_id") `);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(160) NOT NULL, "description" text, "category" character varying(80), "currency" character varying(10) NOT NULL DEFAULT 'INR', "price" integer NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'DRAFT', "thumbnail_url" character varying(512), "content_outline" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "published_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "teacher_id" uuid, CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(160) NOT NULL, "index" integer NOT NULL DEFAULT '0', "section_title" character varying(160), "section_index" integer, "duration_sec" integer NOT NULL DEFAULT '0', "video_cf_uid" character varying(80), "video_cf_playback_id" character varying(80), "video_hls_url" character varying(512), "video_status" character varying(20) NOT NULL DEFAULT 'UPLOADING', "video_meta" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "course_id" uuid, CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" integer NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'INR', "payment_provider" character varying(32) NOT NULL DEFAULT 'UNKNOWN', "provider_order_id" character varying(80), "provider_payment_id" character varying(80), "status" character varying(16) NOT NULL DEFAULT 'CREATED', "meta" jsonb, "purchased_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "course_id" uuid, CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7b12fe23d6ff77c32f908a1b3f" ON "purchases" ("provider_order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_651aba6185c021782e7f2113c9" ON "purchases" ("provider_payment_id") `);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_024ddf7e04177a07fcb9806a90a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_69e6c77f4f1b4dbdbcc218157d9" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_69e6c77f4f1b4dbdbcc218157d9"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_024ddf7e04177a07fcb9806a90a"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_651aba6185c021782e7f2113c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b12fe23d6ff77c32f908a1b3f"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9dea74916617da4a95c8cce52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69e1783e301281de8f86190080"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
